### ISSUE TITLE
For a Link Post, remove leading and tailing whitespace so as to not end up with an invalid URL  

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#111]
When a URL would be invalid because of leading or trailing whitespace, the value for the input field for "url" can be trimmed (strip both leading and trailing whitespace) before then checking for validation.   

While there is an existing issue regarding URL validation, Issue #14, this is a remedy that can be applied before doing that validation.

SN [Item #12470](https://stacker.news/items/12470) is an example of a link Post that was submitted with leading whitespace, causing the url to get formatted "http://%20%20https//blog.hashrateindex.com/a-bitcoin-miners-guide-to-bitcoin-upgrades".  Trimming the leading and lagging whitespace first will result in a correct URL.

**Comment by huumn** [comment]
fixed locally

**Comment by cointastical** [comment]
I'm still seeing a problem related to malformed URLs. 

A link with a trailing space gets:  

```invalid url```

This can easily happen if copying the URL from a web page (e.g., using mouse to drag and select some text).

I think a .trim() is all that is needed yet, as that would fix any of the extraneous whitespace either leading or trailing the URL
