### ISSUE TITLE
For dup detection with Youtube shortened links, ignore query string

### ISSUE THREAD

**Issue by cointastical** [stackernews/stacker.news#221]
For example, dup detection should (I believe) determine the following to be a duplicate of each other:
https://youtu.be/aBC123Def45
https://youtu.be/aBC123Def45?t=123
  
Dup detection is properly seeing a duplicate when the post is for a regular Youtube link (and not the URL shortener):
https://www.youtube.com/watch?v=aBC123Def45
https://www.youtube.com/watch?v=aBC123Def45&t=123

It's possible this was some unwanted side-effect when implementing a fix for Issue #62.

**Comment by cointastical** [comment]
There's also the situation where the Youtube shortened link will be a redirect to a Youtube.com link that has a query string.  And that isn't properly being checked for duplicates either.

Example:

https://youtu.be/aBC123Def45
might redirect to:
https://www.youtube.com/watch?v=aBC123Def45&feature=youtu.be

That would not be seen as a duplicate of the following Link post (likely it is the case that whatever gets done to dups check to ignore the query string isn't also being done for the link redirect as well):
https://www.youtube.com/watch?v=aBC123Def45

An example of this occuring was SN [Item #119135[(https://stacker.news/items/119135)

**Comment by huumn** [comment]
Thanks for recording all these. Eventually, we'll be able to get a really good dupe detection thing going.

**Comment by huumn** [comment]
Fixed locally.

**Comment by cointastical** [comment]
This ticket was closed however I'm still seeing an instance where Dupes detection isn't catching it.

If I try to post either of these two:
https://youtu.be/7JWNuSgQgMw
https://www.youtube.com/live/7JWNuSgQgMw

With both of those, SN will correctly show [Item #119135](https://stacker.news/items/119135) as a Dupe.
But [Item #119088](https://stacker.news/items/119088) will not be shown.   The youtube link for 119088 doesn't have the www. prefix, so possibly that is the reason it was not found.

If so, then it appears the fix to Issue #169 did not work properly here.

**Comment by huumn** [comment]
We just weren't checking for the `/live` variation of the youtube link. I've fixed this locally and will ship it with the next more significant update.
