### ISSUE TITLE
profile image not shown

### ISSUE THREAD

**Issue by llamabyte** [stackernews/stacker.news#385]
I noticed this happens with some other profiles aswell.

It might be a browser issue though as i noticed it happens on some QR images too.

![2](https://github.com/stackernews/stacker.news/assets/130471564/200298ea-92ef-427d-acb1-9c0277e915be)

**Comment by huumn** [comment]
Which other profiles?

Can you share the image you are trying to upload so I can attempt to recreate it?

**Comment by llamabyte** [comment]
It's rare, only notice it every 100 profiles or so, will search a bit.

**Comment by huumn** [comment]
Can you give this another shot?

There was a bug related to images. I think it's fixed now

**Comment by llamabyte** [comment]
still happening. recent image 
![sn](https://github.com/stackernews/stacker.news/assets/130471564/a7159873-82c2-4cab-b36c-cfa70b8f3cbe)

**Comment by ekzyis** [comment]
Yes, can confirm: https://stacker.news/llamabyte
