### ISSUE TITLE
Display contribution from rewards when hovering over an items sats

### ISSUE THREAD

**Issue by ekzyis** [stackernews/stacker.news#684]
How can it say 465 sats in total but only one stacker zapped and I zapped 100? Am I just confused or does this really not look right? lol

https://github.com/stackernews/stacker.news/assets/27162016/27745a26-351c-4629-8c8e-37c117a8cdfd

**Comment by ekzyis** [comment]
![2023-12-17-102341_449x120_scrot](https://github.com/stackernews/stacker.news/assets/27162016/3e0b6572-a3c5-4914-bc9c-1b5dccc48dae)

**Comment by ekzyis** [comment]
Currently unsure how to reproduce. Will wait until we know more when this happens.

**Comment by huumn** [comment]
I think this might've been fixed when I implemented idempotent zapping. Reopen if encountered again.

**Comment by ekzyis** [comment]
Still happening:
![2024-01-07-070606_1920x1080_scrot](https://github.com/stackernews/stacker.news/assets/27162016/9bede9b8-7a6a-4a6b-ba5c-4524c13a6165)

It's this comment: https://stacker.news/items/378901

What do you see?

**Comment by huumn** [comment]
I wonder if this is because rewards add to the comment/post stack count.

**Comment by ekzyis** [comment]
> I wonder if this is because rewards add to the comment/post sats.
> 
> So the `X stackers` is correct, but because you can't see how rewards contributed to the total it's confusing.

Ah, this would make sense.

**Comment by huumn** [comment]
This no longer happens
